### ISSUE TITLE
Updating readme.md

### ISSUE THREAD

**Issue by Unnimaya6122004** [SmartGrid-ETHIndia/Smart-grid#72]
### Describe the feature

to add the logo of gssoc ,discord server link at the top of readme.md

### Add ScreenShots

![Screenshot from 2024-05-17 05-42-25](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/130051152/fda842d0-f9a5-4193-af4d-f97113fa633e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Unnimaya6122004** [comment]
can u pls assign me this issue ..

**Comment by aasthakourav20** [comment]
Hey @Mayank2808sharma  , A Readme file plays an important role in User/Contributor convenience . It is essential in any given repository because it serves as the primary source of information about the project. It provides an overview of the project's purpose, how to install and use it, and any necessary prerequisites. Additionally, the README often includes guidelines for contributing, links to documentation, and contact information for the maintainers.
Let's create a more descriptive , attention seeking README file including all guidelines .

Kindly assign this issue to me under GSSoC'24 .

**Comment by Unnimaya6122004** [comment]
i think u should create a new issue for this....

**Comment by Mayank2808sharma** [comment]
it already has good readme no need
